### ISSUE TITLE
particle rendering problem

### ISSUE THREAD

**Issue by samwong92** [msolids/musen#20]
For v1.73.0, no problem occur.
I downloaded the newest v1.74.1 and installed the Visual C++ Redistributable for Visual Studio 2022 for it.
All the particles render as dark black and changing coloring also fails, while geometry is fine. Any idea?
Below is the image for particles free falling inside a cylinderical_container.

*Further confirmed that, v1.73.1 works fine, v1.74.0 failed on the same issue.

![image](https://github.com/user-attachments/assets/72edd008-9696-4204-a6c2-3a7585434435)

**Comment by vasylskorych** [comment]
@samwong92 , try Options -> Settings -> Particle Textures -> Pick... and select e.g. the first texture.
