### ISSUE TITLE
Export as text inaccuracy

### ISSUE THREAD

**Issue by juwoha** [msolids/musen#7]
Hi Vasyl,

i noticed a accuracy problem when using the "Export as text" function. I used the Package Generator to fill a scene with particles. I set the max_overlap to 1e-05 mm. After generating, I checked the max_overlap in the object editor, which reads 9.8e-06. Than I use the "export as text" function and reload the saved file with the "import from text" function. Checking the object editor again, the maximum overlap now is 0.00012.

Can you check what is going on please?

I am using Musen 1.73.1 Build 230120.161242.409f6bc3.open running with Windows 10.

**Comment by vasylskorych** [comment]
Hi,

Did you try to increase export precision via File -> Export as text -> Properties -> Additional settings -> TD precision?

**Comment by juwoha** [comment]
Hi,

i apologize for the complaint. You are right, setting a higher TD precision "fixed" the problem. I failed to see that option or respectively was looking at the wrong place.

Thank you very much for your quick response and for your support!
